### ISSUE TITLE
Add note suggesting not to use Resolved for ticket status

### ISSUE THREAD

**Issue by CarrieBrown** [opensciencegrid/campus-research#8]
Similar to what software did here: https://opensciencegrid.org/technology/policy/software-support/#freshdesk

**Comment by lmichael107** [comment]
Hi Carrie,

Given that OSG Connect engages with end users, our history of reviewing the
survey responses, and the ongoing likelihood that NSF expects data on
end-use satisfaction, we really should keep using "Resolved". We are
importantly different from other OSG areas and ticket topics, for this
reason.

Lauren

Lauren Michael - Research Computing Facilitator, Center for High Throughput
Computing <http://chtc.cs.wisc.edu/>, University of Wisconsin - Madison
Other Affiliations: Wisconsin Institute for Discovery
<http://wid.wisc.edu/people/lauren-michael/>; Open Science Grid
<https://opensciencegrid.org/>; CaRCC <https://carcc.org/>
lmichael@wisc.edu, tinyurl.com/LMichaelCalendar, Discovery 2262,
(608)316-4430

**Comment by CarrieBrown** [comment]
That is a fair point. I will continue to use resolved then.

Thank you for the clarification Lauren!

**Comment by lmichael107** [comment]
You can always choose NOT to use it, depending on the circumstances. Happy to discuss with the RF group.
